"""Add calendar_events and integrations tables

Revision ID: 5750435ca4eb
Revises: 
Create Date: 2026-01-26 21:02:20.845925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5750435ca4eb'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('integration_type', sa.Enum('CALDAV', 'GOOGLE_CALENDAR', 'OUTLOOK_CALENDAR', name='integrationtype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('sync_direction', sa.Enum('TO_CALENDAR', 'FROM_CALENDAR', 'BIDIRECTIONAL', name='syncdirection'), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=True),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('external_event_id', sa.String(), nullable=True),
    sa.Column('external_calendar_id', sa.String(), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', 'CONFLICT', name='calendarsyncstatus'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('conflict_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['external_calendar_id'], ['integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: ALTER COLUMN statements removed as SQLite does not support them
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_events')
    op.drop_table('integrations')
    # Note: ALTER COLUMN statements removed as SQLite does not support them
    # ### end Alembic commands ###
